version: '3'

services:
  frontend:
    command: yarn start
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend/:/usr/src/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    ports:
      - '3000:3000'

  backend:
    command: sh -c "yarn run migrate-up-prod && yarn dev"
    build: ./backend
    stdin_open: true
    volumes:
      - ./backend/:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://ohtu_user:ohtupassword@userdata:5432/account_database
    depends_on:
      - userdata
    restart: on-failure:10

  userdata:
    image: 'postgres'
    env_file:
      - ./userdata/userdata.env
    volumes:
      - userdata-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  language-server:
    image: 'ohtuamandus/robot-language-server'
    ports:
      - '5555:5555'

volumes:
  userdata-data:
